apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: tlzdvmowj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tlzdvmowj-python 
  name: tlzdvmowj-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tlzdvmowj-python
    weight: 100 
