apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tlzdvmowj-python-gitops
  description: This is GitOps manifest for tlzdvmowj-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: tlzdvmowj-python
    jenkins.io/job-full-name: tlzdvmowj-python-gitops
    backstage.io/kubernetes-id: tlzdvmowj-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tlzdvmowj-python
